apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 1
  labels:
    run: cfuldemo
  name: cfuldemo
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: cfuldemo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cfuldemo
    spec:
      containers:
      - image: mrgeometro/cfuldemo:frist
        imagePullPolicy: IfNotPresent
        name: cfuldemo
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
